### ISSUE TITLE
Unable to install on macOS Sonoma

### ISSUE THREAD

**Issue by remino** [jonboh/shai#1]
Trying `cargo install shai`, but I’m getting the following:

```
❯ cargo install shai
    Updating crates.io index
  Installing shai v0.1.1
error: failed to compile `shai v0.1.1`, intermediate artifacts can be found at `/var/folders/zy/17xcp3xx6vb3q0qnfh06185h0000gn/T/cargo-install7meZgt`

Caused by:
  failed to select a version for the requirement `clap = "^4.3"`
  candidate versions found which didn't match: 3.2.25, 3.2.24, 3.2.23, ...
  location searched: crates.io index
  required by package `shai v0.1.1`
```

I’m not that well versed in Go, but looks like a package management problem. My crates.io seems up to date when I search for packages:

```
❯ cargo search shai
shai = "0.1.1"                        # A shell AI assistant
[redacted]
❯ cargo search clap
clap = "4.4.6"                             # A simple to use, efficient, and full-featured Command Line Argument Parser
[redacted]
```

I also tried cloning the repo and updating `Cargo.toml` to use `clap 4.4`:

```
diff --git a/Cargo.toml b/Cargo.toml
index 18e0061..e50f524 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -15,7 +15,7 @@ exclude = ["assets/*"]
 # See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
 
 [dependencies]
-clap = { version = "4.3", features = ["derive"] }
+clap = { version = "4.4", features = ["derive"] }
 serde = { version = "1.0", features = ["derive"] }
 serde_yaml = "0.9.22"
 serde_json = "1.0"
```

But I’m having the same issue:

```
❯ cargo install --path .
  Installing shai v0.1.1 ([redacted]/shai)
    Updating crates.io index
error: failed to compile `shai v0.1.1 ([redacted]/shai)`, intermediate artifacts can be found at `/Users/remi/Sites/shai/target`

Caused by:
  failed to select a version for the requirement `clap = "^4.4"`
  candidate versions found which didn't match: 3.2.25, 3.2.24, 3.2.23, ...
  location searched: crates.io index
  required by package `shai v0.1.1 ([redacted]/shai)`
```

Not sure what’s going on here.

**Comment by jonboh** [comment]
That's strange, it seems to build correctly on the CI for macos-13 (that's Sonoma right?). I don't have any macos in which to test it manually.
Can you check the cargo and rustup versions?
```
cargo version
rustup --version
rustc --version
```

Also, can you try running the same commands as the CI on a clone of shai (on the latest commit without modification)?
```
rustup update stable && rustup default stable
cargo build --verbose
cargo test --verbose
```
Let me know the result :)

**Comment by remino** [comment]
Sorry for the late reply. Thanks for checking in.

So I checked the versions, as you suggested, and saw them being a bit old:

```
cargo 1.56.0 (4ed5d137b 2021-10-04)
rustup 1.24.3 (ce5817a94 2021-05-31)
rustc 1.56.1 (59eed8a2a 2021-11-01)
```

Then I did you second series of command. Build went fine. Tests were okay! 👍 

I checked the versions again. They got updated after `rustup update`:

```
cargo 1.73.0 (9c4383fb5 2023-08-26)
rustup 1.26.0 (5af9b9484 2023-04-05)
rustc 1.73.0 (cc66ad468 2023-10-03)
```

So, I tried doing both an install from local and from the cargo repo:

```sh
cargo install --path .
# Worked okay!
cargo uninstall shai
cargo install shai
# Worked okay too!
```

Everything went fine and now I can run `shai` as expected.

So turns out I just had to update `rustup`. Shows you how much I know it and how much I use it. ;)

Thanks!

PS: I did ask ChatGPT about the error before coming here. Even that couldn’t give me a solution. Humans are not obsolete yet.

**Comment by jonboh** [comment]
Happy to see we could fix it! :D
